name: shop

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - 80:3000
    volumes:
      - ./frontend/src:/usr/src/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
  backend:
    build: ./backend
    ports:
      - 8080:8080
      - 5005:5005
    volumes:
      - ./backend/target/classes:/app/classes
      - ./backend/target/dependency:/app/dependency
    depends_on:
      - database
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shop
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql

  


