name: shop

services:
  frontend:
    build: ./frontend
    ports:
      - 80:3000
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    develop:
      watch:
        - action: rebuild
          path: ./frontend/package.json
  backend:
    build: ./backend
    ports:
      - 8080:8080
      - 5005:5005
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shop
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql

  


