name: shop

services:
  frontend:
    build: 
      context: ./frontend
      no_cache: true
    ports:
      - 80:3000
    volumes:
      - ./frontend/src:/usr/src/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
    develop:
      watch:
        - action: rebuild
          path: ./frontend/package.json
  backend:
    build: ./backend
    ports:
      - 8080:8080
      - 5005:5005
    volumes:
      - ./backend/target/classes:/app/classes
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shop
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql

  


