FROM maven:3.9-eclipse-temurin-17 AS builder
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests && \
    java -Djarmode=layertools -jar target/*.jar extract

FROM eclipse-temurin:17-jdk
WORKDIR /app

# Spring Boot puts class files into /application
COPY --from=builder /app/application/ /app/classes/
COPY --from=builder /app/dependencies/ /app/dependency/
COPY --from=builder /app/snapshot-dependencies/ /app/dependency/

EXPOSE 8080 5005

ENTRYPOINT ["java", \
  "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", \
  "-cp", "/app/classes:/app/dependency/*", \
  "github.com.mattbutcher_swe.shop_backend.ShopBackendApplication"]
